FROM visgateai/inference-image:latest

WORKDIR /app

COPY requirements-video.txt /app/requirements-video.txt

RUN pip install --no-cache-dir -r requirements-video.txt

COPY app/ /app/app/
COPY pipelines/ /app/pipelines/

ENV VISGATE_WORKER_PROFILE=video

CMD ["python3", "-m", "app.video_worker"]